version: "2.3"

networks:
  default:
    name: pompei-mongo-debug-network

services:

  mongo:                #              docker exec -it mybpm-debug-mongo mongo
    image: mongo:5.0.5
    container_name: pmd-mongo
    mem_limit: 700M
    restart: always
    ports:
      - "11011:27017"
    volumes:
      - ~/volumes/pmd/mongo:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d
    command:
      - docker-entrypoint.sh
      - --bind_ip_all
      - --replSet
      - main

  mongo-express:
    image: mongo-express:0.54.0
    container_name: pmd-mongo-express
    mem_limit: 200M
    restart: always
    depends_on:
      - mongo
    ports:
      - "11012:8081"                                        # MONGO   http://localhost:11012
    environment:
      ME_CONFIG_OPTIONS_EDITORTHEME: cobalt
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: 111
      ME_CONFIG_MONGODB_SERVER: mongo
